-- Mohamed Ali shared Supabase setup
-- Run this file once from Supabase SQL Editor or the authenticated Supabase MCP.

create table if not exists public.career_submissions (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone_number text not null,
  email text not null,
  field text not null,
  years_of_experience text not null,
  availability text not null,
  training_sector_experience boolean not null default false,
  cv_url text not null,
  cv_file_name text,
  message text,
  status text not null default 'New' check (status in ('New','Reviewed','Shortlisted','Contacted','Archived')),
  last_contacted_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.career_history (
  id bigint generated by default as identity primary key,
  company text not null,
  role text not null,
  year text not null,
  copy text not null,
  copy_ar text,
  highlights jsonb not null default '[]'::jsonb,
  highlights_ar jsonb not null default '[]'::jsonb,
  logo text,
  sort_order integer not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.broadcast_history (
  id bigint generated by default as identity primary key,
  job_title text not null,
  job_details text not null,
  contact_name text,
  contact_email text,
  contact_linkedin text,
  other_instructions text,
  recipient_count integer not null default 0,
  success_count integer not null default 0,
  failure_count integer not null default 0,
  audience_type text not null default 'all' check (audience_type in ('all','field','test')),
  audience_field text,
  created_at timestamptz not null default now()
);

create index if not exists career_history_order_idx on public.career_history (published, sort_order);
create index if not exists career_submissions_created_idx on public.career_submissions (created_at desc);

alter table public.career_submissions enable row level security;
alter table public.career_history enable row level security;
alter table public.broadcast_history enable row level security;

drop policy if exists "public can submit career applications" on public.career_submissions;
create policy "public can submit career applications" on public.career_submissions for insert to anon, authenticated with check (true);
drop policy if exists "admins can read career applications" on public.career_submissions;
create policy "admins can read career applications" on public.career_submissions for select to authenticated using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
drop policy if exists "published career history is public" on public.career_history;
create policy "published career history is public" on public.career_history for select to anon, authenticated using (published = true);
drop policy if exists "admins manage career history" on public.career_history;
create policy "admins manage career history" on public.career_history for all to authenticated using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin') with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
drop policy if exists "admins read broadcast history" on public.broadcast_history;
create policy "admins read broadcast history" on public.broadcast_history for select to authenticated using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

grant select on public.career_history to anon, authenticated;
grant insert on public.career_submissions to anon, authenticated;
grant select on public.career_submissions, public.broadcast_history to authenticated;
