-- Run after the Supabase MCP OAuth connection is verified.
create table if not exists public.career_history (
  id bigint generated by default as identity primary key,
  company text not null,
  role text not null,
  year text not null,
  copy text not null,
  copy_ar text,
  highlights jsonb not null default '[]'::jsonb,
  highlights_ar jsonb not null default '[]'::jsonb,
  logo text,
  sort_order integer not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.career_history enable row level security;
create policy "published career history is public" on public.career_history for select to anon, authenticated using (published = true);
create index if not exists career_history_public_order_idx on public.career_history (published, sort_order);
